apiVersion: v1
kind: Service
metadata:
  name: test-vm
spec:
  ports:
  - name: nodeport
    nodePort: 30000
    port: 27017
    protocol: TCP
    targetPort: 22
  selector:
    vm.kubevirt.io/name: test-vm
  type: NodePort
