apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kubevirt-hyperconverged
spec:
  channel: stable
  installPlanApproval: Automatic
  name: kubevirt-hyperconverged
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  config:
    env:
    # HTTP proxy settings
    - name: HTTP_PROXY
      value: ''
    - name: HTTPS_PROXY
      value: ''
    - name: NO_PROXY
      value: ''
