apiVersion: hco.kubevirt.io/v1beta1
kind: HyperConverged
metadata:
  name: kubevirt-hyperconverged
spec:
  infra: {}
  workloads:
    nodePlacement:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/baremetal
